### ISSUE TITLE
Decisions about data structures

### ISSUE THREAD

**Issue by dimitristaufer** [dimitristaufer/opensense-openhab-master#14]
At this stage we should have:
- Decided which HTTP REST Framework we will use and have imported it into our project

We have to decide about local data structures, before we can do any further implementation.

For example, we GET a sensors temperature JSON block. How will we store the data? A "master class" called "Sensor", which has several child classes like "Temp_Sensor", "Wind_Sensor". And these child classes have additional attributes.

**Comment by MaksymKoliesnikov** [comment]
Pros and contras of RESTful frameworks:

https://www.gajotres.net/best-available-java-restful-micro-frameworks/

https://www.quora.com/Whats-the-best-RESTful-web-framework-to-use-with-Java

**Comment by dimitristaufer** [comment]
Thanks @MaksymKoliesnikov  - this issues is about the data structure though. I'll comment on issue #7.
