### ISSUE TITLE
Find new user stories based on progress

### ISSUE THREAD

**Issue by dimitristaufer** [dimitristaufer/opensense-openhab-master#8]
Find new user stories, especially in the context of polygons

**Comment by dimitristaufer** [comment]
Test

**Comment by MaksymKoliesnikov** [comment]
Storie 1:
    Da ich umziehe, bin auf der Suche nach neuer Wohnung. Für mich ist es wichtig, dass man ruhig von zu Hause arbeiten kann bzw. abends nach der Arbeit sich erholen kann. Aus diesem Grund will ich Information darüber bekommen, wie laut es an bestimmten Orten ist. Mithilfe von Polygonen kann Infos zur Verfügung gestellt stellen, wie laut es in der Nähe von dem Hause, auf der Straße, im Bezirk und allgemein im Stadt ist.
Optional kann man bestimmte Zeiträume eingeben, die besonders von Interesse sind. 

Was wird benötigt:
* Datenquelle (OpenSense?)
* Parameter: noise
* Koordinaten (latitude und longitude)
* Zeitraum (von bis)
* Da wir nur indoor Daten haben können, ist der Stockwerk für uns irrelevant

Darstellungsmöglichkeiten:
* Ein Graph, wie sich den Lärm an einem bestimmten Platz entwickelt.
* Ein Graph, wie sich den Lärm an einem bestimmten Platz und  Zeit entwickelt.
* Vorschläge, welche Bezirke interessant sein können, wenn man bestimmte Bedingungen angibt ( zB. wo ist am wenigsten Lärm in der Zeit von 20:00 bis 07:00 und dabei nur Zone AB von Berlin betrachten oder nur bestimmte Bezirke auswählt).

**Comment by MaksymKoliesnikov** [comment]
Storie 2:
    Wir sind eine Familie mit kleinen Kinder, die sich um Gesundheit kümmert. Am Wochenende mögen wir alle gerne zu spazieren und neue Plätze entdecken. Wegen der starken Industrialisierung von großen Städten muss man sich mit solchen Werten, wie pm10 und pm2,5 bekannt machen. Mithilfe von Polygonen und einer Datenquelle kann man herausfinden, wo es sich am besten lohnt zu spazieren.
Optional: Man gibt 2 Koordinaten an und es wird einen Weg zwischen den beiden erstellt, der  „am saubersten“ sein soll. 

Was wird benötigt:
* Datenquelle (OpenSense)
* Parameter: pm10 und pm2,5
* Koordinaten (latitude und longitude)

Darstellungsmöglichkeiten:
* Visualisierung des Änderungen vom Stickoxidwert bei mir zuhause (alte User Storie, die wir bereits haben)
*  Vorschläge, wo man am besten spazieren gehen kann (evtl. Parks einbinden und die dann zum Auswahl vorschlagen)
* Optional: den Weg zwischen 2 Koordinaten

**Comment by MaksymKoliesnikov** [comment]
Storie 3:
    Die Storie muss sich mit Temperatur beschäftigen und IFTT einbeziehen. Möglichst beste Werte dafür soll mithilfe von Polygonen gestellt werden. 

Was wird benötigt:
* Datenquelle
* Parameter: temperature, niederschlag?
* Koordinaten

Darstellungsmöglichkeiten:
* Es wird täglich um bestimmter Uhrzeit eine Nachricht mit der Information über das Wetter verschickt.
* Es können Unter-/Obergrenzen angegeben werden, bei denen eine bestimmte Nachricht gesendet wird.
* Es wird eine Nachricht, wenn sich der Wert vom Niederschlag ändert.

**Comment by dimitristaufer** [comment]
> Storie 2:
> Wir sind eine Familie mit kleinen Kinder, die sich um Gesundheit kümmert. Am Wochenende mögen wir alle gerne zu spazieren und neue Plätze entdecken. Wegen der starken Industrialisierung von großen Städten muss man sich mit solchen Werten, wie pm10 und pm2,5 bekannt machen. Mithilfe von Polygonen und einer Datenquelle kann man herausfinden, wo es sich am besten lohnt zu spazieren.
> Optional: Man gibt 2 Koordinaten an und es wird einen Weg zwischen den beiden erstellt, der „am saubersten“ sein soll.
> 
> Was wird benötigt:
> 
> * Datenquelle (OpenSense)
> * Parameter: pm10 und pm2,5
> * Koordinaten (latitude und longitude)
> 
> Darstellungsmöglichkeiten:
> 
> * Visualisierung des Änderungen vom Stickoxidwert bei mir zuhause (alte User Storie, die wir bereits haben)
> * Vorschläge, wo man am besten spazieren gehen kann (evtl. Parks einbinden und die dann zum Auswahl vorschlagen)
> * Optional: den Weg zwischen 2 Koordinaten

Interessante Idee! Allerdings hat das noch wenig mit SmartHome und openHAB zu tun, oder?

**Comment by dimitristaufer** [comment]
> Storie 1:
> Da ich umziehe, bin auf der Suche nach neuer Wohnung. Für mich ist es wichtig, dass man ruhig von zu Hause arbeiten kann bzw. abends nach der Arbeit sich erholen kann. Aus diesem Grund will ich Information darüber bekommen, wie laut es an bestimmten Orten ist. Mithilfe von Polygonen kann Infos zur Verfügung gestellt stellen, wie laut es in der Nähe von dem Hause, auf der Straße, im Bezirk und allgemein im Stadt ist.
> Optional kann man bestimmte Zeiträume eingeben, die besonders von Interesse sind.
> 
> Was wird benötigt:
> 
> * Datenquelle (OpenSense?)
> * Parameter: noise
> * Koordinaten (latitude und longitude)
> * Zeitraum (von bis)
> * Da wir nur indoor Daten haben können, ist der Stockwerk für uns irrelevant
> 
> Darstellungsmöglichkeiten:
> 
> * Ein Graph, wie sich den Lärm an einem bestimmten Platz entwickelt.
> * Ein Graph, wie sich den Lärm an einem bestimmten Platz und  Zeit entwickelt.
> * Vorschläge, welche Bezirke interessant sein können, wenn man bestimmte Bedingungen angibt ( zB. wo ist am wenigsten Lärm in der Zeit von 20:00 bis 07:00 und dabei nur Zone AB von Berlin betrachten oder nur bestimmte Bezirke auswählt).

Super, dass du dir weitere Gedanken zu diesen Nutzerszenario gemacht hast. Wir sollten bedenken, dass es bei OpenSense lediglich um Outdoor-Daten geht und wir Indoor-Lautstärkewerte explizit aufgrund von Datenschutzrichtlinien, nicht einfach verwenden dürfen.
Eventuell könnt ihr beim morgigen Tutorium noch einmal nachfragen. Letzte Woche war die Antwort allerdings ziemlich klar. Und zwar, dass so etwas viel zu viele datenschutzrechtliche Probleme aufweist und eher unerwünscht ist.
